name: Save your life
favicon: null
layout_spectrum: 0.96089
typography_spectrum: 0.3216
title: Save your life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.444213486276567
  rhythmicContrast: 0.9473054769914597
purpose: []
